OTT_APP="
com.netflix.mediaclient
com.amazon.avod.thirdpartyclient
com.disney.disneyplus
com.hulu.plus
com.hbo.hbonow
com.apple.atve
com.peacocktv.peacockandroid
com.cbs.ott
com.sling
"
DIALER_APP="
com.oneplus.dialer
com.motorola.motodialer
com.google.android.dialer
com.truecaller
com.android.incallui
com.oplus.dialer
"
BROWSER_APP="
com.android.chrome
org.mozilla.firefox
com.microsoft.emmx
com.opera.browser
com.sec.android.app.sbrowser
com.brave.browser
com.duckduckgo.mobile.android
com.vivaldi.browser
com.google.android.apps.chrome
idm.internet.download.manager.plus
"
VIDEO_APP="
org.videolan.vlc
com.mxtech.videoplayer.ad
com.kmplayer
com.plexapp.android
com.gretech.gomplayerko
video.player.videoplayer
com.bsplayer.bspandroid.free
video.player.videoplayer
xmw.app.plex
net.fixthephoto.videoeditor
"
BENCHMARK_APP="
com.primatelabs.geekbench
com.primatelabs.geekbench6
Geekbench
com.antutu.ABenchMark
com.futuremark.dmandroid.application
net.kishonti.gfxbench.gl.v50000
com.futuremark.pcmark.android.benchmark
com.andromeda.androbench2 com.cpuid.cpu_z
com.passmark.pt_mobile
com.a1dev.sdbench
com.aurorasoftworks.quadrant.ui.standard
"
MGAME_APP="
com.activision.callofduty.shooter
com.supercell.clashofclans
com.supercell.clashroyale
com.madfingergames.legends
com.studiowildcard.wardrumstudios.ark
"
TGAME_APP="
com.tencent.ig
com.pubg.imobile
com.pubg.krmobile
com.epicgames.fortnite
com.miHoYo.genshin
com.gameloft.android.ANMP.GloftA9HM
com.pearlabyss.blackdesertm
com.pearlabyss.blackdesertm.gl
"
