CAMERA_APP="
com.motorola.camera2
com.oneplus.camera
com.xiaomi.camera
com.google.android.GoogleCamera
com.shamim.camera
net.sourceforge.opencamera
com.flavionet.android.camera.pro
com.footej.camera
com.riseupgames.proshot2
com.marginz.snap
com.halide.marki
com.shopmoment.momentprocamera
"
OTT_APP="
com.netflix.mediaclient
com.amazon.avod.thirdpartyclient
com.disney.disneyplus
com.hulu.plus
com.hbo.hbonow
com.apple.atve
com.peacocktv.peacockandroid
com.cbs.ott
com.sling
com.crunchyroll.crunchyroid
com.instagram.android
com.facebook.katana
com.facebook.lite
com.facebook.mlite
com.facebook.orca
"
DIALER_APP="
com.oneplus.dialer
com.motorola.motodialer
com.google.android.dialer
com.truecaller
com.android.incallui
com.oplus.dialer
"
BROWSER_APP="
com.android.chrome
org.mozilla.firefox
com.microsoft.emmx
com.opera.browser
com.sec.android.app.sbrowser
com.brave.browser
com.duckduckgo.mobile.android
com.vivaldi.browser
com.google.android.apps.chrome
idm.internet.download.manager.plus
"
VIDEO_APP="
org.videolan.vlc
com.mxtech.videoplayer.ad
com.kmplayer
com.plexapp.android
com.gretech.gomplayerko
video.player.videoplayer
com.bsplayer.bspandroid.free
video.player.videoplayer
xmw.app.plex
net.fixthephoto.videoeditor
"
BENCHMARK_APP="
com.primatelabs.geekbench
com.primatelabs.geekbench6
Geekbench
com.antutu.ABenchMark
com.futuremark.dmandroid.application
net.kishonti.gfxbench.gl.v50000
com.futuremark.pcmark.android.benchmark
com.andromeda.androbench2 com.cpuid.cpu_z
com.passmark.pt_mobile
com.a1dev.sdbench
com.aurorasoftworks.quadrant.ui.standard
"
MGAME_APP="
com.activision.callofduty.shooter
com.supercell.clashofclans
com.supercell.clashroyale
com.madfingergames.legends
com.studiowildcard.wardrumstudios.ark
air.com.ubisoft.brawl.halla.platform.fighting.action.pvp
com.Psyonix.RL2D
"
TGAME_APP="
com.tencent.ig
com.pubg.imobile
com.pubg.krmobile
com.epicgames.fortnite
com.miHoYo.genshin
com.gameloft.android.ANMP.GloftA9HM
com.pearlabyss.blackdesertm
com.pearlabyss.blackdesertm.gl
com.Mediatonic.FallGuys_client
com.levelinfinite.sgameGlobal.midaspay
com.garena.game.kgvn
com.YoStarEN.Arknights
com.kurogame.wutheringwaves.global
"
